
# GET All
GET http://localhost:8686/api/v1/users HTTP/1.1

###

# GET by ID
GET http://localhost:8686/api/v1/users/1 HTTP/1.1

###

# Create new User

POST http://localhost:8686/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTY5MzE5NTk3Nn0.f2jzUhqqhQhPX09rVh38NAqy6tb3Hjpj4NF4OYLL-GU

{   
  "firstName": "Nguyen",
  "lastName": "Van B",
  "email": "nguyenvanb@example.com",
  "numberPhone": "0988777111",
  "birthday": "",
  "address": "",
  "password": "12345678"
}

### 

# Update User

PUT http://localhost:8686/api/v1/users/84 HTTP/1.1
content-type: application/json

{   
  "firstName": "Nguyen",
  "lastName": "Van B",
}

###
# Update User Token

PUT http://localhost:8686/api/v1/users/6 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTY5MzE5NTk3Nn0.f2jzUhqqhQhPX09rVh38NAqy6tb3Hjpj4NF4OYLL-GU

{   
  "firstName": "Nguyen",
  "lastName": "Van C"
}



###
DELETE  http://localhost:8686/api/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoiam9obmRvZUBleGFtcGxlLmNvbSIsImlhdCI6MTY5MzE5NTk3Nn0.f2jzUhqqhQhPX09rVh38NAqy6tb3Hjpj4NF4OYLL-GU

{
  "id": 6
}


