### Lay ALl
GET http://localhost:3000/employees

###

GET http://localhost:3000/employees/65059350b3d574437b00a9f3


###

GET http://localhost:3000/employees/phone/Hai


### Them moi

POST http://localhost:9000/employees
content-type: application/json

{
    "firstName": "Tuan3",
    "lastName": "Vo3",
    "email": "votuan3@gmail.com",
    "phoneNumber": "9988776655",
    "address": "38 yen bai",
    "password": "38yenbai"
}

### Update


PUT  http://localhost:9000/employees/65059292b3d574437b00a9f6
content-type: application/json

{
    "password": "1234567890"
}

###

DELETE  http://localhost:3000/employees/65059350b3d574437b00a9f7
